archimedes/silverstripe/api/urls.py
from archimedes.api.urls import router

from ..api import views

# Register viewsets with the router created in api.urls
router.register(r'silverstripe/sites', views.SilverStripeSiteViewSet)
router.register(
    r'silverstripe/advisory_sources',
    views.SilverStripeAdvisorySourceViewSet,
    base_name='silverstripe/advisory_sources'
)
router.register(
    r'silverstripe/advisories',
    views.SilverStripeAdvisoryViewSet,
    base_name='silverstripe/advisories'
)

# No URL patterns needed - they're done by api.urls.router
urlpatterns = []

archimedes/silverstripe/models.py
import re
from functools import total_ordering
from unidecode import unidecode

# Built in but undocumented
# from https://stackoverflow.com/questions/11887762/compare-version-strings-in-python
from distutils.version import LooseVersion

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

from archimedes.sites.models import Site, SiteManager

# Number (. or -) number (. or -) number (. or -) lettersAnd342
VERSION_REGEX = re.compile(r"^v?(\d+)(?:[\.-](\d+))?(?:[\.-](\d+))?(?:[\.-]([\d\w.-]+))?$")


class VersionManager(models.Manager):
    """Used to create a version object from a version string"""

    def parse_version(self, version):
        """Parse a version string into the a Version object"""

        match = VERSION_REGEX.match(version)
        if not match:
            raise ValueError("Not a version string")

        return self.create(
            major=match.group(1),
            minor=match.group(2) if match.lastindex > 1 else 0,
            patch=match.group(3) if match.lastindex > 2 else 0,
            extra=match.group(4) if match.lastindex > 3 else ''
        )


# Total ordering means we only need to implement two comparison functions
# to use them all
@total_ordering
class Version(models.Model):
    """A normalized version object"""
    objects = VersionManager()

    major = models.PositiveIntegerField()
    minor = models.PositiveIntegerField(blank=True, default=0)
    patch = models.PositiveIntegerField(blank=True, default=0)
    extra = models.CharField(max_length=20, blank=True, null=True, default='')

    def __str__(self):
        return "%d.%d.%d-%s" % (self.major, self.minor, self.patch, self.extra)

    def __gt__(self, version2):
        # Would love to know if there's a version of this which doesn't fall
        # down stairs
        if self.major != version2.major:
            if self.minor != version2.minor:
                if self.patch != version2.patch:
                    if self.extra != version2.extra:
                        return self.extra > version2.extra

                    return False
                return self.extra > version2.extra
            return self.minor > version2.minor
        return self.major > version2.major

    def __eq__(self, version2):
        try:
            return self.major == version2.major and \
                self.minor == version2.minor and \
                self.patch == version2.patch and \
                self.extra.lower().strip() == version2.lower().strip()
        except AttributeError:
            return isinstance(self, None) and isinstance(version2, None)


class Project(models.Model):
    """A module or theme in a site"""
    # In future we could include information from
    # http://addons.silverstripe.org/add-ons
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField(auto_now=True)
    custom = models.BooleanField(default=False)
    type = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.slug

    @property
    def type_name(self):
        if self.type == 'project_module':
            return 'Module'
        elif self.type == 'project_theme':
            return 'Theme'
        return 'Project'

    @property
    def sites_using(self):
        return SilverStripeSite.objects.filter(modules__project__pk=self.pk)

    @property
    def sites_vulnerable(self):
        """All sites that have a release of this project that contain an advisory"""
        return SilverStripeSite.objects.filter(modules__project__pk=self.pk, modules__advisories__isnull=False)


class ReleaseManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super(ReleaseManager, self).get_queryset().select_related('project')


class Release(models.Model):
    """A release of a project, such as a theme or model"""
    objects = ReleaseManager()

    project = models.ForeignKey('Project', related_name='releases', related_query_name='release')
    url = models.URLField()
    date = models.DateTimeField(blank=True, null=True)
    date_updated = models.DateTimeField(auto_now=True)
    version = models.ForeignKey('Version')

    class Meta:
        ordering = ['-version', '-date']

    @property
    def slug(self):
        return self.project.slug + ':' + self.version

    def __str__(self):
        return self.slug


class SilverStripeSite(Site):
    label = 'SilverStripe'
    objects = SiteManager()

    php_version = models.ForeignKey('Version', blank=True, null=True, related_name="php_version_site")
    silverstripe_version = models.ForeignKey(
        'Version', blank=True, null=True,
        related_name="silverstripe_version_site"
    )

    slogan = models.CharField(max_length=200, blank=True)
    revisions = models.PositiveIntegerField(blank=True, null=True)
    users = models.PositiveIntegerField(blank=True, null=True)

    modules = models.ManyToManyField(
        Release, related_name='site_modules', related_query_name='module_site', blank=True
    )
    themes = models.ManyToManyField(
        Release, related_name='site_themes',
        related_query_name='theme_site', blank=True
    )

    # A count of users in the system.
    users = models.PositiveIntegerField(blank=True, null=True, help_text='Number of users on site')

    def compare_json_against_latest_report(self, report_json, field_paths=None):
        """
        Check whether report has unexpected values based on last report from this site.
        Return a dict of changed fields and their old values. If no field_paths argument
        is specified, a default_fields set may be used.
        """
        default_field_paths = ['ReportType', ['Environment', 'Name'], ['Environment', 'Label'], 'ServerHostname']
        if field_paths is None:
            field_paths = default_field_paths

        latest = self.reports.latest('date_received')
        return latest.compare_json(report_json, field_paths=field_paths)

    @property
    def core_vulnerabilities(self):
        """Returns any vulnerabilities for this core (Framework/CMS) version"""
        # TODO return Advisory.objects.filter(affected_sites__in=self)
        return 0

    @property
    def vulnerability_count(self):
        """Return total count of vulnerable components."""
        count = (1 if self.core_vulnerabilities > 0 else 0)
        count += len(self.vulnerable_modules)
        count += len(self.vulnerable_themes)
        return count

    @property
    def vulnerable_modules(self):
        """All releases in self.modules that have an advisory"""
        return Release.objects.filter(module_site=self, advisories__pk__isnull=False).distinct()

    @property
    def vulnerable_themes(self):
        """All releases in self.themes that have an advisory"""
        return Release.objects.filter(theme_site=self, advisories__pk__isnull=False).distinct()


class Advisory(models.Model):
    STATUS = (
        ('downloaded', 'Downloaded'),
        ('parsed', 'Needs Review'),
        ('reviewed', 'Reviewed'),
        ('ignored', 'Ignored'),
        ('failed', 'Parsing Failed'),
    )

    guid = models.CharField(max_length=200, unique=True)
    title = models.CharField(max_length=200)
    url = models.URLField()
    source = models.ForeignKey('AdvisorySource', default=None)

    description = models.TextField()
    # Unparsed summary element
    raw_summary = models.TextField()

    date_posted = models.DateTimeField(null=True, blank=True)
    date_parsed = models.DateTimeField(null=True, blank=True)

    ignored = models.BooleanField(default=False)
    failed = models.BooleanField(default=False)
    reviewer = models.ForeignKey(User, null=True, blank=True, related_name='ss_advisory')
    status = models.CharField(max_length=50, choices=STATUS, default='downloaded')

    advisory_id = models.CharField(max_length=200, blank=True)

    # TODO This is limited to SilverStripe's security feed
    risk = models.CharField(max_length=50, choices=(
        ('low', 'Low'),
        ('moderate', 'Moderate'),
        ('important', 'Important'),
        ('critical', 'Critical')
    ))

    versions_affected = models.CharField(max_length=50, null=True, blank=True)
    versions_fixed = models.CharField(max_length=50, null=True, blank=True)

    affected_sites = models.ManyToManyField(SilverStripeSite)

    class Meta:
        ordering = ['-date_posted']
        verbose_name_plural = 'Advisories'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """Set the status before saving"""
        if self.ignored:
            self.status = 'ignored'
        elif self.failed:
            self.status = 'failed'
        elif not self.date_parsed:
            self.status = 'downloaded'
        elif self.reviewer:
            self.status = 'reviewed'
        else:
            self.status = 'parsed'
        super(Advisory, self).save(*args, **kwargs)

    def affected(self, version):
        """Check if version is affected by this advisory"""
        # TODO Update this to work with the Version model rather than version strings.
        # Should be a simpler than the current method (I think)
        # Match a single version number
        singlereg = r"([1-9](?:(?:\.d)|(?:-[a-zA-Z0-9]+))*)"

        # Build a list of conditions
        single = []
        between = []
        less = []

        def match_ver_str(version, version_string):
            for part in version_string.split(','):
                # If the part is a range of versions
                m = re.match(r"%s\s+to|-\s+%s" % (singlereg, singlereg))
                if m:
                    between.append((m.group(1), m.group(2)))

                # If the part is less than a version

archimedes/silverstripe/templates/silverstripe/advisory_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}Advisory: {{ advisory }}{% endblock page_header %}

{% block main-ng-controller %}{% endblock main-ng-controller %}

{% block main %}
<div class="row">
    <div class="col-sm-12 push-15">
        <a href="{% url 'silverstripe:advisory-list' %}" class="btn btn-primary btn-sm" role="button">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back to Advisories
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Metadata</div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>GUID</th>
                            <td>{{ advisory.guid }}</td>
                        </tr>
                        <tr>
                            <th>Title</th>
                            <td>{{ advisory.title }}</td>
                        </tr>
                        <tr>
                            <th>URL</th>
                            <td>{{ advisory.url|urlize }}</td>
                        </tr>
                        <tr>
                            <th>Source</th>
                            <td>{{ advisory.source }}</td>
                        </tr>
                        <tr>
                            <th>Date Posted</th>
                            <td>{{ advisory.date_posted }}</td>
                        </tr>
                        <tr>
                            <th>Date Parsed</th>
                            <td>{{ advisory.date_parsed }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>
                                <span class="label drupal-advisory-label-{{ advisory.status }}">{{ advisory.get_status_display }}</span>
                                {% if advisory.status == 'reviewed' %} by {{ advisory.reviewer }}{% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>Sites Affected</th>
                            <td>
                                {% if affected %}
                                <p><span class="label label-danger">{{ affected|length }} site{{ affected|length|pluralize }} affected</span><p/>
                                <ul>
                                    {% for silverstripesite in affected %}
                                    <li><a href="{% url 'sites:site-detail' silverstripesite.pk %}"><span class="environment">[{{ drupalsite.environment }}]</span> {{ silverstripesite }}</a></li>
                                    {% endfor %}
                                </ul>
                                {% else %}
                                <span class="label label-success">No sites affected</span>
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Parsed Data</div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    {% if advisory.date_parsed %}
                    <tr>
                        <th>Advisory ID</th>
                        <td>{{ advisory.advisory_id }}</td>
                    </tr>
                    <tr>
                        <th>Risk</th>
                        <td>{{ advisory.risk }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ advisory.description }}</td>
                    </tr>
                    <tr>
                        <th>Versions Affected</th>
                        <td>{{ advisory.versions_affected }}</td>
                    </tr>
                    <tr>
                        <th>Versions Fixed</th>
                        <td>{{ advisory.versions_fixed }}</td>
                    </tr>

                    {% else %}
                    <tr>
                        <td colspan="2">This advisory has not yet been parsed</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

archimedes/silverstripe/templates/silverstripe/advisory_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}Advisories{% endblock page_header %}

{% block main-ng-controller %}ssAdvisoryListController{% endblock main-ng-controller %}

{% block main %}
<div class="row">
    <div class="col-lg-8 push-15">
        <ul class="nav nav-pills">
            <li ng-class="{ active: filter == ''}"><a href="#" ng-click="filter = ''">All</a></li>
            {% for source in advisory_sources %}
            <li ng-class="{ active: filter == '{{source.slug}}'}">
                <a href="#" ng-click="filter = '{{source.slug}}'">{{source.title}}</a>
            </li>
            {% endfor %}
        </ul>
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-4 push-15">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search advisories..." ng-model="search" ng-model-options="{ debounce: 100 }">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
        </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
</div>

<table class="table table-bordered table-hover push-50" infinite-scroll="loadAdvisories()"
       infinite-scroll-distance="1" infinite-scroll-listen-for-event="advisories:updated" ng-cloak>
    <thead>
        <tr>
            <th>Title</th>
            <th>Affected</th>
            <th>Source</th>
            <th>Date</th>
            <th>Risk</th>
            <th>Status</th>
        </tr>
    </thead>
    {% verbatim %}
    <tbody>
        <tr ng-repeat="advisory in advisories">
            <td><a href="{% endverbatim %}{% url 'silverstripe:advisory-list' %}{% verbatim %}{{ advisory.pk }}">{{ advisory.title }}</a></td>
            <td align="right">{{ advisory.affected_sites.length ? advisory.affected_sites.length : '&mdash;' }}</td>
            <td>{{ advisory.source }}</td>
            <td><span>{{ advisory.date_posted | amUtc | amDateFormat:'lll' }}</span></td>
            <td class="capitalise">{{ advisory.risk }}</td>
            <td class="capitalise">{{ advisory.status }}</td>
        </tr>
        <tr ng-show="!loading && advisories.length == 0">
            <td colspan="6">No advisories</td>
        </tr>
    </tbody>
    {% endverbatim %}
</table>
<span us-spinner="{radius:8, width:3, length: 6, lines: 11, opacity: 0.1, speed: 1.2}" class="spinner" spinner-on="loading"></span >
{% endblock main %}

{% block javascript-angular %}
{{ block.super }}
<script src="{% static 'theme/js/controllers/ssadvisoryListController.js' %}"></script>
{% endblock javascript-angular %}

archimedes/silverstripe/templates/silverstripe/module_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}Modules &amp; Themes{% endblock page_header %}

{% block main-ng-controller %}SilverStripeModuleListController{% endblock main-ng-controller %}

{% block main %}
<div class="row">
    <div class="col-lg-8 push-15">
        <ul class="nav nav-pills">
            <li ng-class="{ active: filter == ''}"><a href="#" ng-click="filter = ''">All</a></li>
            <li ng-class="{ active: filter == 'silverstripe-module'}"><a href="#" ng-click="filter = 'project_module'">Modules</a></li>
            <li ng-class="{ active: filter == 'silverstripe-theme'}"><a href="#" ng-click="filter = 'project_theme'">Themes</a></li>
        </ul>
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-4 push-15">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search modules &amp; themes..." ng-model="search" ng-model-options="{ debounce: 100 }">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
        </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
</div>
<table class="table table-bordered table-hover push-50"
       infinite-scroll="loadModules()" infinite-scroll-distance="1" infinite-scroll-listen-for-event="modules:updated" ng-cloak>
    <thead>
        <tr>
            <th>Name</th>
            <th>Slug</th>
            <th>Sites Using</th>
            <th>URL</th>
        </tr>
    </thead>
    {% verbatim %}
    <tbody>
        <tr ng-repeat="module in modules">
            <td><a href="{% endverbatim %}{% url 'silverstripe:module-list' %}{% verbatim %}{{ module.pk }}">
                {{ module.name }}
                <span ng-if="!module.name" class='text-muted'>(no name)</span>
            </a></td>
            <td>{{ module.slug }}</td>
            <td align="right">{{ module.sites_using.length ? module.sites_using.length : '&mdash;'}}</td>
            <td><a href="{{ module.url }}" target="_blank">{{ module.url }}</a></td>
        </tr>
        <tr ng-show="!loading && modules.length == 0">
            <td colspan="5">No modules or themes</td>
        </tr>
    </tbody>
    {% endverbatim %}
</table>
<span us-spinner="{radius:8, width:3, length: 6, lines: 11, opacity: 0.1, speed: 1.2}" class="spinner" spinner-on="loading"></span >
{% endblock main %}

{% block javascript-angular %}
{{ block.super }}
<script src="{% static 'theme/js/controllers/ssmoduleListController.js' %}"></script>
{% endblock javascript-angular %}